# Generated by Django 5.1.7 on 2025-03-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('trainee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('img', models.ImageField(upload_to='trainee/image')),
                ('isactive', models.BooleanField(default=True)),
            ],
        ),
    ]
